window.esdocSearchIndex = [
  [
    "baseapp/js/features/common/directives/accordiandirective.js~accordiandirective",
    "class/js/features/common/directives/AccordianDirective.js~AccordianDirective.html",
    "<span>AccordianDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/directives/AccordianDirective.js</span>",
    "class"
  ],
  [
    "baseapp/js/main.js~app",
    "class/js/main.js~App.html",
    "<span>App</span> <span class=\"search-result-import-path\">baseApp/js/main.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/lib/apphttpresponseinterceptor.js~apphttpresponseinterceptor",
    "class/js/fw/lib/AppHttpResponseInterceptor.js~AppHttpResponseInterceptor.html",
    "<span>AppHttpResponseInterceptor</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/AppHttpResponseInterceptor.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/config/appconfig.js~configurator",
    "class/js/fw/config/AppConfig.js~Configurator.html",
    "<span>Configurator</span> <span class=\"search-result-import-path\">baseApp/js/fw/config/AppConfig.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/config/notifierconfig.js~configurator",
    "class/js/fw/config/NotifierConfig.js~Configurator.html",
    "<span>Configurator</span> <span class=\"search-result-import-path\">baseApp/js/fw/config/NotifierConfig.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/config/routerconfig.js~configurator",
    "class/js/fw/config/RouterConfig.js~Configurator.html",
    "<span>Configurator</span> <span class=\"search-result-import-path\">baseApp/js/fw/config/RouterConfig.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/config/ssoconfig.js~configurator",
    "class/js/fw/config/SSOConfig.js~Configurator.html",
    "<span>Configurator</span> <span class=\"search-result-import-path\">baseApp/js/fw/config/SSOConfig.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/lib/configuratorbase.js~configuratorbase",
    "class/js/fw/lib/ConfiguratorBase.js~ConfiguratorBase.html",
    "<span>ConfiguratorBase</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/ConfiguratorBase.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/service/customfilters.js~customfilters",
    "class/js/fw/service/CustomFilters.js~CustomFilters.html",
    "<span>CustomFilters</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/CustomFilters.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/league_table/main.js~feature",
    "class/js/features/common/league_table/main.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/league_table/main.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/player_details/main.js~feature",
    "class/js/features/common/player_details/main.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/player_details/main.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/rss_feed/main.js~feature",
    "class/js/features/common/rss_feed/main.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/rss_feed/main.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/team_details/main.js~feature",
    "class/js/features/common/team_details/main.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/team_details/main.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/ui/accordian.js~feature",
    "class/js/features/common/ui/Accordian.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/ui/Accordian.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/ui/footer.js~feature",
    "class/js/features/common/ui/Footer.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/ui/Footer.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/ui/routeindicator.js~feature",
    "class/js/features/common/ui/RouteIndicator.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/ui/RouteIndicator.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/ui/topnavbar.js~feature",
    "class/js/features/common/ui/TopNavbar.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/ui/TopNavbar.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/home/main.js~feature",
    "class/js/features/home/main.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">baseApp/js/features/home/main.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/lib/featurebase.js~featurebase",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html",
    "<span>FeatureBase</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/FeatureBase.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/service/footballdataservice.js~footballdataservice",
    "class/js/fw/service/FootballDataService.js~FootballDataService.html",
    "<span>FootballDataService</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/FootballDataService.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/directives/footerdirective.js~footerdirective",
    "class/js/features/common/directives/FooterDirective.js~FooterDirective.html",
    "<span>FooterDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/directives/FooterDirective.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/home/controller/homecontroller.js~homecontroller",
    "class/js/features/home/controller/HomeController.js~HomeController.html",
    "<span>HomeController</span> <span class=\"search-result-import-path\">baseApp/js/features/home/controller/HomeController.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/home/directives/homedirective.js~homedirective",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html",
    "<span>HomeDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/home/directives/HomeDirective.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/lib/initbase.js~initbase",
    "class/js/fw/lib/InitBase.js~InitBase.html",
    "<span>InitBase</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/InitBase.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/init/body.js~initializer",
    "class/js/fw/init/Body.js~Initializer.html",
    "<span>Initializer</span> <span class=\"search-result-import-path\">baseApp/js/fw/init/Body.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/init/header.js~initializer",
    "class/js/fw/init/Header.js~Initializer.html",
    "<span>Initializer</span> <span class=\"search-result-import-path\">baseApp/js/fw/init/Header.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/init/validator.js~initializer",
    "class/js/fw/init/Validator.js~Initializer.html",
    "<span>Initializer</span> <span class=\"search-result-import-path\">baseApp/js/fw/init/Validator.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html",
    "<span>LeagueTableController</span> <span class=\"search-result-import-path\">baseApp/js/features/common/league_table/controller/LeagueTableController.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html",
    "<span>LeagueTableDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/league_table/directives/LeagueTableDirective.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/directives/topnavbardirective.js~navigationdirective",
    "class/js/features/common/directives/TopNavbarDirective.js~NavigationDirective.html",
    "<span>NavigationDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/directives/TopNavbarDirective.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html",
    "<span>PlayerDetailsController</span> <span class=\"search-result-import-path\">baseApp/js/features/common/player_details/controller/PlayerDetailsController.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html",
    "<span>PlayerDetailsDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/player_details/directives/PlayerDetailsDirective.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/service/rssservice.js~rssservice",
    "class/js/fw/service/RSSService.js~RSSService.html",
    "<span>RSSService</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/RSSService.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/rss_feed/controller/rssfeedcontroller.js~rssfeedcontroller",
    "class/js/features/common/rss_feed/controller/RssFeedController.js~RssFeedController.html",
    "<span>RssFeedController</span> <span class=\"search-result-import-path\">baseApp/js/features/common/rss_feed/controller/RssFeedController.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/rss_feed/directives/rssfeeddirective.js~rssfeeddirective",
    "class/js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective.html",
    "<span>RssFeedDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/rss_feed/directives/RssFeedDirective.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/service/events.js~service",
    "class/js/fw/service/Events.js~Service.html",
    "<span>Service</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/Events.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/service/utils.js~service",
    "class/js/fw/service/Utils.js~Service.html",
    "<span>Service</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/Utils.js</span>",
    "class"
  ],
  [
    "baseapp/js/fw/lib/servicebase.js~servicebase",
    "class/js/fw/lib/ServiceBase.js~ServiceBase.html",
    "<span>ServiceBase</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/ServiceBase.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html",
    "<span>TeamDetailsController</span> <span class=\"search-result-import-path\">baseApp/js/features/common/team_details/controller/TeamDetailsController.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html",
    "<span>TeamDetailsDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/team_details/directives/TeamDetailsDirective.js</span>",
    "class"
  ],
  [
    "baseapp/js/features/common/controllers/topnavbarcontroller.js~topnavbarcontroller",
    "function/index.html#static-function-TopNavbarController",
    "<span>TopNavbarController</span> <span class=\"search-result-import-path\">baseApp/js/features/common/controllers/TopNavbarController.js</span>",
    "function"
  ],
  [
    "baseapp/js/main.js~app",
    "variable/index.html#static-variable-app",
    "<span>app</span> <span class=\"search-result-import-path\">baseApp/js/main.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/lib/apphttpresponseinterceptor.js~apphttpresponseinterceptor",
    "variable/index.html#static-variable-appHttpResponseInterceptor",
    "<span>appHttpResponseInterceptor</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/AppHttpResponseInterceptor.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/config/appconfig.js~configurator",
    "variable/index.html#static-variable-configurator",
    "<span>configurator</span> <span class=\"search-result-import-path\">baseApp/js/fw/config/AppConfig.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/config/notifierconfig.js~configurator",
    "variable/index.html#static-variable-configurator",
    "<span>configurator</span> <span class=\"search-result-import-path\">baseApp/js/fw/config/NotifierConfig.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/config/routerconfig.js~configurator",
    "variable/index.html#static-variable-configurator",
    "<span>configurator</span> <span class=\"search-result-import-path\">baseApp/js/fw/config/RouterConfig.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/config/ssoconfig.js~configurator",
    "variable/index.html#static-variable-configurator",
    "<span>configurator</span> <span class=\"search-result-import-path\">baseApp/js/fw/config/SSOConfig.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/lib/configuratorbase.js~configuratorbase",
    "variable/index.html#static-variable-configuratorBase",
    "<span>configuratorBase</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/ConfiguratorBase.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/service/customfilters.js~customfilters",
    "variable/index.html#static-variable-customFilters",
    "<span>customFilters</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/CustomFilters.js</span>",
    "variable"
  ],
  [
    "baseapp/js/features/common/rss_feed/main.js~feature",
    "variable/index.html#static-variable-feature",
    "<span>feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/rss_feed/main.js</span>",
    "variable"
  ],
  [
    "baseapp/js/features/common/team_details/main.js~feature",
    "variable/index.html#static-variable-feature",
    "<span>feature</span> <span class=\"search-result-import-path\">baseApp/js/features/common/team_details/main.js</span>",
    "variable"
  ],
  [
    "baseapp/js/features/home/main.js~feature",
    "variable/index.html#static-variable-feature",
    "<span>feature</span> <span class=\"search-result-import-path\">baseApp/js/features/home/main.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/lib/featurebase.js~featurebase",
    "variable/index.html#static-variable-featureBase",
    "<span>featureBase</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/FeatureBase.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/service/footballdataservice.js~footballdataservice",
    "variable/index.html#static-variable-footballDataService",
    "<span>footballDataService</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/FootballDataService.js</span>",
    "variable"
  ],
  [
    "baseapp/js/features/common/directives/footerdirective.js~footerdirective",
    "variable/index.html#static-variable-footerDirective",
    "<span>footerDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/directives/FooterDirective.js</span>",
    "variable"
  ],
  [
    "baseapp/js/features/home/directives/homedirective.js~homedirective",
    "variable/index.html#static-variable-homeDirective",
    "<span>homeDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/home/directives/HomeDirective.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/lib/initbase.js~initbase",
    "variable/index.html#static-variable-initBase",
    "<span>initBase</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/InitBase.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/init/body.js~initializer",
    "variable/index.html#static-variable-initializer",
    "<span>initializer</span> <span class=\"search-result-import-path\">baseApp/js/fw/init/Body.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/init/header.js~initializer",
    "variable/index.html#static-variable-initializer",
    "<span>initializer</span> <span class=\"search-result-import-path\">baseApp/js/fw/init/Header.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/init/validator.js~initializer",
    "variable/index.html#static-variable-initializer",
    "<span>initializer</span> <span class=\"search-result-import-path\">baseApp/js/fw/init/Validator.js</span>",
    "variable"
  ],
  [
    "baseapp/js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective",
    "variable/index.html#static-variable-leagueTableDirective",
    "<span>leagueTableDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/league_table/directives/LeagueTableDirective.js</span>",
    "variable"
  ],
  [
    "baseapp/js/features/common/directives/topnavbardirective.js~navigationdirective",
    "variable/index.html#static-variable-navigationDirective",
    "<span>navigationDirective</span> <span class=\"search-result-import-path\">baseApp/js/features/common/directives/TopNavbarDirective.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/lib/omit.js~omit",
    "function/index.html#static-function-omit",
    "<span>omit</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/Omit.js</span>",
    "function"
  ],
  [
    "baseapp/js/fw/lib/pluck.js~pluck",
    "function/index.html#static-function-pluck",
    "<span>pluck</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/Pluck.js</span>",
    "function"
  ],
  [
    "baseapp/js/fw/service/rssservice.js~rssservice",
    "variable/index.html#static-variable-rSSService",
    "<span>rSSService</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/RSSService.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/service/events.js~service",
    "variable/index.html#static-variable-service",
    "<span>service</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/Events.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/service/utils.js~service",
    "variable/index.html#static-variable-service",
    "<span>service</span> <span class=\"search-result-import-path\">baseApp/js/fw/service/Utils.js</span>",
    "variable"
  ],
  [
    "baseapp/js/fw/lib/servicebase.js~servicebase",
    "variable/index.html#static-variable-serviceBase",
    "<span>serviceBase</span> <span class=\"search-result-import-path\">baseApp/js/fw/lib/ServiceBase.js</span>",
    "variable"
  ],
  [
    "baseapp/js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller",
    "variable/index.html#static-variable-teamDetailsController",
    "<span>teamDetailsController</span> <span class=\"search-result-import-path\">baseApp/js/features/common/team_details/controller/TeamDetailsController.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "js/features/common/controllers/topnavbarcontroller.js",
    "file/js/features/common/controllers/TopNavbarController.js.html",
    "js/features/common/controllers/TopNavbarController.js",
    "file"
  ],
  [
    "js/features/common/directives/accordiandirective.js",
    "file/js/features/common/directives/AccordianDirective.js.html",
    "js/features/common/directives/AccordianDirective.js",
    "file"
  ],
  [
    "js/features/common/directives/accordiandirective.js~accordiandirective#constructor",
    "class/js/features/common/directives/AccordianDirective.js~AccordianDirective.html#instance-constructor-constructor",
    "js/features/common/directives/AccordianDirective.js~AccordianDirective#constructor",
    "method"
  ],
  [
    "js/features/common/directives/accordiandirective.js~accordiandirective#link",
    "class/js/features/common/directives/AccordianDirective.js~AccordianDirective.html#instance-method-link",
    "js/features/common/directives/AccordianDirective.js~AccordianDirective#link",
    "method"
  ],
  [
    "js/features/common/directives/accordiandirective.js~accordiandirective#replace",
    "class/js/features/common/directives/AccordianDirective.js~AccordianDirective.html#instance-member-replace",
    "js/features/common/directives/AccordianDirective.js~AccordianDirective#replace",
    "member"
  ],
  [
    "js/features/common/directives/accordiandirective.js~accordiandirective#require",
    "class/js/features/common/directives/AccordianDirective.js~AccordianDirective.html#instance-member-require",
    "js/features/common/directives/AccordianDirective.js~AccordianDirective#require",
    "member"
  ],
  [
    "js/features/common/directives/accordiandirective.js~accordiandirective#restrict",
    "class/js/features/common/directives/AccordianDirective.js~AccordianDirective.html#instance-member-restrict",
    "js/features/common/directives/AccordianDirective.js~AccordianDirective#restrict",
    "member"
  ],
  [
    "js/features/common/directives/accordiandirective.js~accordiandirective#templateurl",
    "class/js/features/common/directives/AccordianDirective.js~AccordianDirective.html#instance-member-templateUrl",
    "js/features/common/directives/AccordianDirective.js~AccordianDirective#templateUrl",
    "member"
  ],
  [
    "js/features/common/directives/accordiandirective.js~accordiandirective#transclude",
    "class/js/features/common/directives/AccordianDirective.js~AccordianDirective.html#instance-member-transclude",
    "js/features/common/directives/AccordianDirective.js~AccordianDirective#transclude",
    "member"
  ],
  [
    "js/features/common/directives/footerdirective.js",
    "file/js/features/common/directives/FooterDirective.js.html",
    "js/features/common/directives/FooterDirective.js",
    "file"
  ],
  [
    "js/features/common/directives/footerdirective.js~footerdirective#constructor",
    "class/js/features/common/directives/FooterDirective.js~FooterDirective.html#instance-constructor-constructor",
    "js/features/common/directives/FooterDirective.js~FooterDirective#constructor",
    "method"
  ],
  [
    "js/features/common/directives/footerdirective.js~footerdirective#link",
    "class/js/features/common/directives/FooterDirective.js~FooterDirective.html#instance-method-link",
    "js/features/common/directives/FooterDirective.js~FooterDirective#link",
    "method"
  ],
  [
    "js/features/common/directives/footerdirective.js~footerdirective#replace",
    "class/js/features/common/directives/FooterDirective.js~FooterDirective.html#instance-member-replace",
    "js/features/common/directives/FooterDirective.js~FooterDirective#replace",
    "member"
  ],
  [
    "js/features/common/directives/footerdirective.js~footerdirective#restrict",
    "class/js/features/common/directives/FooterDirective.js~FooterDirective.html#instance-member-restrict",
    "js/features/common/directives/FooterDirective.js~FooterDirective#restrict",
    "member"
  ],
  [
    "js/features/common/directives/footerdirective.js~footerdirective#templateurl",
    "class/js/features/common/directives/FooterDirective.js~FooterDirective.html#instance-member-templateUrl",
    "js/features/common/directives/FooterDirective.js~FooterDirective#templateUrl",
    "member"
  ],
  [
    "js/features/common/directives/topnavbardirective.js",
    "file/js/features/common/directives/TopNavbarDirective.js.html",
    "js/features/common/directives/TopNavbarDirective.js",
    "file"
  ],
  [
    "js/features/common/directives/topnavbardirective.js~navigationdirective#constructor",
    "class/js/features/common/directives/TopNavbarDirective.js~NavigationDirective.html#instance-constructor-constructor",
    "js/features/common/directives/TopNavbarDirective.js~NavigationDirective#constructor",
    "method"
  ],
  [
    "js/features/common/directives/topnavbardirective.js~navigationdirective#link",
    "class/js/features/common/directives/TopNavbarDirective.js~NavigationDirective.html#instance-method-link",
    "js/features/common/directives/TopNavbarDirective.js~NavigationDirective#link",
    "method"
  ],
  [
    "js/features/common/directives/topnavbardirective.js~navigationdirective#replace",
    "class/js/features/common/directives/TopNavbarDirective.js~NavigationDirective.html#instance-member-replace",
    "js/features/common/directives/TopNavbarDirective.js~NavigationDirective#replace",
    "member"
  ],
  [
    "js/features/common/directives/topnavbardirective.js~navigationdirective#restrict",
    "class/js/features/common/directives/TopNavbarDirective.js~NavigationDirective.html#instance-member-restrict",
    "js/features/common/directives/TopNavbarDirective.js~NavigationDirective#restrict",
    "member"
  ],
  [
    "js/features/common/directives/topnavbardirective.js~navigationdirective#templateurl",
    "class/js/features/common/directives/TopNavbarDirective.js~NavigationDirective.html#instance-member-templateUrl",
    "js/features/common/directives/TopNavbarDirective.js~NavigationDirective#templateUrl",
    "member"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js",
    "file/js/features/common/league_table/controller/LeagueTableController.js.html",
    "js/features/common/league_table/controller/LeagueTableController.js",
    "file"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#config",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-member-config",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#config",
    "member"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#constructor",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-constructor-constructor",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#constructor",
    "method"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#filter",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-member-filter",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#filter",
    "member"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#getleaguetable",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-method-getLeagueTable",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#getLeagueTable",
    "method"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#gettabletopper",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-method-getTableTopper",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#getTableTopper",
    "method"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#getteamdetails",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-method-getTeamDetails",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#getTeamDetails",
    "method"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#getteamstats",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-method-getTeamStats",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#getTeamStats",
    "method"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#leagues",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-member-leagues",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#leagues",
    "member"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#run",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-method-run",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#run",
    "method"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#scope",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-member-scope",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#scope",
    "member"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#selectedleague",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-member-selectedLeague",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#selectedLeague",
    "member"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#tables",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-member-tables",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#tables",
    "member"
  ],
  [
    "js/features/common/league_table/controller/leaguetablecontroller.js~leaguetablecontroller#title",
    "class/js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController.html#instance-member-title",
    "js/features/common/league_table/controller/LeagueTableController.js~LeagueTableController#title",
    "member"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js",
    "file/js/features/common/league_table/directives/LeagueTableDirective.js.html",
    "js/features/common/league_table/directives/LeagueTableDirective.js",
    "file"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective#bindtocontroller",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html#instance-member-bindToController",
    "js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective#bindToController",
    "member"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective#constructor",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html#instance-constructor-constructor",
    "js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective#constructor",
    "method"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective#controller",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html#instance-member-controller",
    "js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective#controller",
    "member"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective#controlleras",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html#instance-member-controllerAs",
    "js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective#controllerAs",
    "member"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective#link",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html#instance-method-link",
    "js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective#link",
    "method"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective#replace",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html#instance-member-replace",
    "js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective#replace",
    "member"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective#restrict",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html#instance-member-restrict",
    "js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective#restrict",
    "member"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective#scope",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html#instance-member-scope",
    "js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective#scope",
    "member"
  ],
  [
    "js/features/common/league_table/directives/leaguetabledirective.js~leaguetabledirective#templateurl",
    "class/js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective.html#instance-member-templateUrl",
    "js/features/common/league_table/directives/LeagueTableDirective.js~LeagueTableDirective#templateUrl",
    "member"
  ],
  [
    "js/features/common/league_table/main.js",
    "file/js/features/common/league_table/main.js.html",
    "js/features/common/league_table/main.js",
    "file"
  ],
  [
    "js/features/common/league_table/main.js~feature#beforestart",
    "class/js/features/common/league_table/main.js~Feature.html#instance-method-beforeStart",
    "js/features/common/league_table/main.js~Feature#beforeStart",
    "method"
  ],
  [
    "js/features/common/league_table/main.js~feature#constructor",
    "class/js/features/common/league_table/main.js~Feature.html#instance-constructor-constructor",
    "js/features/common/league_table/main.js~Feature#constructor",
    "method"
  ],
  [
    "js/features/common/league_table/main.js~feature#execute",
    "class/js/features/common/league_table/main.js~Feature.html#instance-method-execute",
    "js/features/common/league_table/main.js~Feature#execute",
    "method"
  ],
  [
    "js/features/common/main.js",
    "file/js/features/common/main.js.html",
    "js/features/common/main.js",
    "file"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js",
    "file/js/features/common/player_details/controller/PlayerDetailsController.js.html",
    "js/features/common/player_details/controller/PlayerDetailsController.js",
    "file"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller#addlisteners",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html#instance-method-addListeners",
    "js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController#addListeners",
    "method"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller#changesorting",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html#instance-method-changeSorting",
    "js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController#changeSorting",
    "method"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller#constructor",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html#instance-constructor-constructor",
    "js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController#constructor",
    "method"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller#filter",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html#instance-member-filter",
    "js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController#filter",
    "member"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller#getteamplayers",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html#instance-method-getTeamPlayers",
    "js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController#getTeamPlayers",
    "method"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller#playerdetailslistener",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html#instance-member-playerDetailsListener",
    "js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController#playerDetailsListener",
    "member"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller#players",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html#instance-member-players",
    "js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController#players",
    "member"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller#run",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html#instance-method-run",
    "js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController#run",
    "method"
  ],
  [
    "js/features/common/player_details/controller/playerdetailscontroller.js~playerdetailscontroller#sort",
    "class/js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController.html#instance-member-sort",
    "js/features/common/player_details/controller/PlayerDetailsController.js~PlayerDetailsController#sort",
    "member"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js",
    "file/js/features/common/player_details/directives/PlayerDetailsDirective.js.html",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js",
    "file"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective#bindtocontroller",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html#instance-member-bindToController",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective#bindToController",
    "member"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective#constructor",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html#instance-constructor-constructor",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective#constructor",
    "method"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective#controller",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html#instance-member-controller",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective#controller",
    "member"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective#controlleras",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html#instance-member-controllerAs",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective#controllerAs",
    "member"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective#link",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html#instance-method-link",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective#link",
    "method"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective#replace",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html#instance-member-replace",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective#replace",
    "member"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective#restrict",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html#instance-member-restrict",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective#restrict",
    "member"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective#scope",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html#instance-member-scope",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective#scope",
    "member"
  ],
  [
    "js/features/common/player_details/directives/playerdetailsdirective.js~playerdetailsdirective#templateurl",
    "class/js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective.html#instance-member-templateUrl",
    "js/features/common/player_details/directives/PlayerDetailsDirective.js~PlayerDetailsDirective#templateUrl",
    "member"
  ],
  [
    "js/features/common/player_details/main.js",
    "file/js/features/common/player_details/main.js.html",
    "js/features/common/player_details/main.js",
    "file"
  ],
  [
    "js/features/common/player_details/main.js~feature#beforestart",
    "class/js/features/common/player_details/main.js~Feature.html#instance-method-beforeStart",
    "js/features/common/player_details/main.js~Feature#beforeStart",
    "method"
  ],
  [
    "js/features/common/player_details/main.js~feature#constructor",
    "class/js/features/common/player_details/main.js~Feature.html#instance-constructor-constructor",
    "js/features/common/player_details/main.js~Feature#constructor",
    "method"
  ],
  [
    "js/features/common/player_details/main.js~feature#execute",
    "class/js/features/common/player_details/main.js~Feature.html#instance-method-execute",
    "js/features/common/player_details/main.js~Feature#execute",
    "method"
  ],
  [
    "js/features/common/rss_feed/controller/rssfeedcontroller.js",
    "file/js/features/common/rss_feed/controller/RssFeedController.js.html",
    "js/features/common/rss_feed/controller/RssFeedController.js",
    "file"
  ],
  [
    "js/features/common/rss_feed/controller/rssfeedcontroller.js~rssfeedcontroller#constructor",
    "class/js/features/common/rss_feed/controller/RssFeedController.js~RssFeedController.html#instance-constructor-constructor",
    "js/features/common/rss_feed/controller/RssFeedController.js~RssFeedController#constructor",
    "method"
  ],
  [
    "js/features/common/rss_feed/controller/rssfeedcontroller.js~rssfeedcontroller#feeds",
    "class/js/features/common/rss_feed/controller/RssFeedController.js~RssFeedController.html#instance-member-feeds",
    "js/features/common/rss_feed/controller/RssFeedController.js~RssFeedController#feeds",
    "member"
  ],
  [
    "js/features/common/rss_feed/controller/rssfeedcontroller.js~rssfeedcontroller#getrssfeed",
    "class/js/features/common/rss_feed/controller/RssFeedController.js~RssFeedController.html#instance-method-getRssFeed",
    "js/features/common/rss_feed/controller/RssFeedController.js~RssFeedController#getRssFeed",
    "method"
  ],
  [
    "js/features/common/rss_feed/controller/rssfeedcontroller.js~rssfeedcontroller#run",
    "class/js/features/common/rss_feed/controller/RssFeedController.js~RssFeedController.html#instance-method-run",
    "js/features/common/rss_feed/controller/RssFeedController.js~RssFeedController#run",
    "method"
  ],
  [
    "js/features/common/rss_feed/directives/rssfeeddirective.js",
    "file/js/features/common/rss_feed/directives/RssFeedDirective.js.html",
    "js/features/common/rss_feed/directives/RssFeedDirective.js",
    "file"
  ],
  [
    "js/features/common/rss_feed/directives/rssfeeddirective.js~rssfeeddirective#bindtocontroller",
    "class/js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective.html#instance-member-bindToController",
    "js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective#bindToController",
    "member"
  ],
  [
    "js/features/common/rss_feed/directives/rssfeeddirective.js~rssfeeddirective#constructor",
    "class/js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective.html#instance-constructor-constructor",
    "js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective#constructor",
    "method"
  ],
  [
    "js/features/common/rss_feed/directives/rssfeeddirective.js~rssfeeddirective#controller",
    "class/js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective.html#instance-member-controller",
    "js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective#controller",
    "member"
  ],
  [
    "js/features/common/rss_feed/directives/rssfeeddirective.js~rssfeeddirective#controlleras",
    "class/js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective.html#instance-member-controllerAs",
    "js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective#controllerAs",
    "member"
  ],
  [
    "js/features/common/rss_feed/directives/rssfeeddirective.js~rssfeeddirective#link",
    "class/js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective.html#instance-method-link",
    "js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective#link",
    "method"
  ],
  [
    "js/features/common/rss_feed/directives/rssfeeddirective.js~rssfeeddirective#replace",
    "class/js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective.html#instance-member-replace",
    "js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective#replace",
    "member"
  ],
  [
    "js/features/common/rss_feed/directives/rssfeeddirective.js~rssfeeddirective#restrict",
    "class/js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective.html#instance-member-restrict",
    "js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective#restrict",
    "member"
  ],
  [
    "js/features/common/rss_feed/directives/rssfeeddirective.js~rssfeeddirective#templateurl",
    "class/js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective.html#instance-member-templateUrl",
    "js/features/common/rss_feed/directives/RssFeedDirective.js~RssFeedDirective#templateUrl",
    "member"
  ],
  [
    "js/features/common/rss_feed/main.js",
    "file/js/features/common/rss_feed/main.js.html",
    "js/features/common/rss_feed/main.js",
    "file"
  ],
  [
    "js/features/common/rss_feed/main.js~feature#beforestart",
    "class/js/features/common/rss_feed/main.js~Feature.html#instance-method-beforeStart",
    "js/features/common/rss_feed/main.js~Feature#beforeStart",
    "method"
  ],
  [
    "js/features/common/rss_feed/main.js~feature#constructor",
    "class/js/features/common/rss_feed/main.js~Feature.html#instance-constructor-constructor",
    "js/features/common/rss_feed/main.js~Feature#constructor",
    "method"
  ],
  [
    "js/features/common/rss_feed/main.js~feature#execute",
    "class/js/features/common/rss_feed/main.js~Feature.html#instance-method-execute",
    "js/features/common/rss_feed/main.js~Feature#execute",
    "method"
  ],
  [
    "js/features/common/rss_feed/main.js~feature#templatecaching",
    "class/js/features/common/rss_feed/main.js~Feature.html#instance-method-templateCaching",
    "js/features/common/rss_feed/main.js~Feature#templateCaching",
    "method"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js",
    "file/js/features/common/team_details/controller/TeamDetailsController.js.html",
    "js/features/common/team_details/controller/TeamDetailsController.js",
    "file"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#addlisteners",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-method-addListeners",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#addListeners",
    "method"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#constructor",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-constructor-constructor",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#constructor",
    "method"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#filter",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-member-filter",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#filter",
    "member"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#getteamdetails",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-method-getTeamDetails",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#getTeamDetails",
    "method"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#getteamfixtures",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-method-getTeamFixtures",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#getTeamFixtures",
    "method"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#name",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-member-name",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#name",
    "member"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#run",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-method-run",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#run",
    "method"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#teamdetails",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-member-teamDetails",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#teamDetails",
    "member"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#teamdetailslistener",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-member-teamDetailsListener",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#teamDetailsListener",
    "member"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#teamfixtures",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-member-teamFixtures",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#teamFixtures",
    "member"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#teamfixtureslistener",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-member-teamFixturesListener",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#teamFixturesListener",
    "member"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#teamid",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-member-teamID",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#teamID",
    "member"
  ],
  [
    "js/features/common/team_details/controller/teamdetailscontroller.js~teamdetailscontroller#teamstats",
    "class/js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController.html#instance-member-teamStats",
    "js/features/common/team_details/controller/TeamDetailsController.js~TeamDetailsController#teamStats",
    "member"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js",
    "file/js/features/common/team_details/directives/TeamDetailsDirective.js.html",
    "js/features/common/team_details/directives/TeamDetailsDirective.js",
    "file"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective#bindtocontroller",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html#instance-member-bindToController",
    "js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective#bindToController",
    "member"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective#constructor",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html#instance-constructor-constructor",
    "js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective#constructor",
    "method"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective#controller",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html#instance-member-controller",
    "js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective#controller",
    "member"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective#controlleras",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html#instance-member-controllerAs",
    "js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective#controllerAs",
    "member"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective#link",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html#instance-method-link",
    "js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective#link",
    "method"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective#replace",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html#instance-member-replace",
    "js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective#replace",
    "member"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective#restrict",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html#instance-member-restrict",
    "js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective#restrict",
    "member"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective#scope",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html#instance-member-scope",
    "js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective#scope",
    "member"
  ],
  [
    "js/features/common/team_details/directives/teamdetailsdirective.js~teamdetailsdirective#templateurl",
    "class/js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective.html#instance-member-templateUrl",
    "js/features/common/team_details/directives/TeamDetailsDirective.js~TeamDetailsDirective#templateUrl",
    "member"
  ],
  [
    "js/features/common/team_details/main.js",
    "file/js/features/common/team_details/main.js.html",
    "js/features/common/team_details/main.js",
    "file"
  ],
  [
    "js/features/common/team_details/main.js~feature#beforestart",
    "class/js/features/common/team_details/main.js~Feature.html#instance-method-beforeStart",
    "js/features/common/team_details/main.js~Feature#beforeStart",
    "method"
  ],
  [
    "js/features/common/team_details/main.js~feature#constructor",
    "class/js/features/common/team_details/main.js~Feature.html#instance-constructor-constructor",
    "js/features/common/team_details/main.js~Feature#constructor",
    "method"
  ],
  [
    "js/features/common/team_details/main.js~feature#execute",
    "class/js/features/common/team_details/main.js~Feature.html#instance-method-execute",
    "js/features/common/team_details/main.js~Feature#execute",
    "method"
  ],
  [
    "js/features/common/team_details/main.js~feature#templatecaching",
    "class/js/features/common/team_details/main.js~Feature.html#instance-method-templateCaching",
    "js/features/common/team_details/main.js~Feature#templateCaching",
    "method"
  ],
  [
    "js/features/common/ui/accordian.js",
    "file/js/features/common/ui/Accordian.js.html",
    "js/features/common/ui/Accordian.js",
    "file"
  ],
  [
    "js/features/common/ui/accordian.js~feature#beforestart",
    "class/js/features/common/ui/Accordian.js~Feature.html#instance-method-beforeStart",
    "js/features/common/ui/Accordian.js~Feature#beforeStart",
    "method"
  ],
  [
    "js/features/common/ui/accordian.js~feature#constructor",
    "class/js/features/common/ui/Accordian.js~Feature.html#instance-constructor-constructor",
    "js/features/common/ui/Accordian.js~Feature#constructor",
    "method"
  ],
  [
    "js/features/common/ui/accordian.js~feature#execute",
    "class/js/features/common/ui/Accordian.js~Feature.html#instance-method-execute",
    "js/features/common/ui/Accordian.js~Feature#execute",
    "method"
  ],
  [
    "js/features/common/ui/footer.js",
    "file/js/features/common/ui/Footer.js.html",
    "js/features/common/ui/Footer.js",
    "file"
  ],
  [
    "js/features/common/ui/footer.js~feature#$body",
    "class/js/features/common/ui/Footer.js~Feature.html#instance-member-$body",
    "js/features/common/ui/Footer.js~Feature#$body",
    "member"
  ],
  [
    "js/features/common/ui/footer.js~feature#beforestart",
    "class/js/features/common/ui/Footer.js~Feature.html#instance-method-beforeStart",
    "js/features/common/ui/Footer.js~Feature#beforeStart",
    "method"
  ],
  [
    "js/features/common/ui/footer.js~feature#constructor",
    "class/js/features/common/ui/Footer.js~Feature.html#instance-constructor-constructor",
    "js/features/common/ui/Footer.js~Feature#constructor",
    "method"
  ],
  [
    "js/features/common/ui/footer.js~feature#execute",
    "class/js/features/common/ui/Footer.js~Feature.html#instance-method-execute",
    "js/features/common/ui/Footer.js~Feature#execute",
    "method"
  ],
  [
    "js/features/common/ui/routeindicator.js",
    "file/js/features/common/ui/RouteIndicator.js.html",
    "js/features/common/ui/RouteIndicator.js",
    "file"
  ],
  [
    "js/features/common/ui/routeindicator.js~feature#$body",
    "class/js/features/common/ui/RouteIndicator.js~Feature.html#instance-member-$body",
    "js/features/common/ui/RouteIndicator.js~Feature#$body",
    "member"
  ],
  [
    "js/features/common/ui/routeindicator.js~feature#constructor",
    "class/js/features/common/ui/RouteIndicator.js~Feature.html#instance-constructor-constructor",
    "js/features/common/ui/RouteIndicator.js~Feature#constructor",
    "method"
  ],
  [
    "js/features/common/ui/routeindicator.js~feature#execute",
    "class/js/features/common/ui/RouteIndicator.js~Feature.html#instance-method-execute",
    "js/features/common/ui/RouteIndicator.js~Feature#execute",
    "method"
  ],
  [
    "js/features/common/ui/routeindicator.js~feature#indicator",
    "class/js/features/common/ui/RouteIndicator.js~Feature.html#instance-method-indicator",
    "js/features/common/ui/RouteIndicator.js~Feature#indicator",
    "method"
  ],
  [
    "js/features/common/ui/topnavbar.js",
    "file/js/features/common/ui/TopNavbar.js.html",
    "js/features/common/ui/TopNavbar.js",
    "file"
  ],
  [
    "js/features/common/ui/topnavbar.js~feature#$body",
    "class/js/features/common/ui/TopNavbar.js~Feature.html#instance-member-$body",
    "js/features/common/ui/TopNavbar.js~Feature#$body",
    "member"
  ],
  [
    "js/features/common/ui/topnavbar.js~feature#beforestart",
    "class/js/features/common/ui/TopNavbar.js~Feature.html#instance-method-beforeStart",
    "js/features/common/ui/TopNavbar.js~Feature#beforeStart",
    "method"
  ],
  [
    "js/features/common/ui/topnavbar.js~feature#constructor",
    "class/js/features/common/ui/TopNavbar.js~Feature.html#instance-constructor-constructor",
    "js/features/common/ui/TopNavbar.js~Feature#constructor",
    "method"
  ],
  [
    "js/features/common/ui/topnavbar.js~feature#execute",
    "class/js/features/common/ui/TopNavbar.js~Feature.html#instance-method-execute",
    "js/features/common/ui/TopNavbar.js~Feature#execute",
    "method"
  ],
  [
    "js/features/common/ui/main.js",
    "file/js/features/common/ui/main.js.html",
    "js/features/common/ui/main.js",
    "file"
  ],
  [
    "js/features/home/routes.js",
    "file/js/features/home/Routes.js.html",
    "js/features/home/Routes.js",
    "file"
  ],
  [
    "js/features/home/controller/homecontroller.js",
    "file/js/features/home/controller/HomeController.js.html",
    "js/features/home/controller/HomeController.js",
    "file"
  ],
  [
    "js/features/home/controller/homecontroller.js~homecontroller#addlisteners",
    "class/js/features/home/controller/HomeController.js~HomeController.html#instance-method-addListeners",
    "js/features/home/controller/HomeController.js~HomeController#addListeners",
    "method"
  ],
  [
    "js/features/home/controller/homecontroller.js~homecontroller#broadcastserviceevent",
    "class/js/features/home/controller/HomeController.js~HomeController.html#instance-method-broadcastServiceEvent",
    "js/features/home/controller/HomeController.js~HomeController#broadcastServiceEvent",
    "method"
  ],
  [
    "js/features/home/controller/homecontroller.js~homecontroller#constructor",
    "class/js/features/home/controller/HomeController.js~HomeController.html#instance-constructor-constructor",
    "js/features/home/controller/HomeController.js~HomeController#constructor",
    "method"
  ],
  [
    "js/features/home/controller/homecontroller.js~homecontroller#run",
    "class/js/features/home/controller/HomeController.js~HomeController.html#instance-method-run",
    "js/features/home/controller/HomeController.js~HomeController#run",
    "method"
  ],
  [
    "js/features/home/directives/homedirective.js",
    "file/js/features/home/directives/HomeDirective.js.html",
    "js/features/home/directives/HomeDirective.js",
    "file"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#bindtocontroller",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-member-bindToController",
    "js/features/home/directives/HomeDirective.js~HomeDirective#bindToController",
    "member"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#constructor",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-constructor-constructor",
    "js/features/home/directives/HomeDirective.js~HomeDirective#constructor",
    "method"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#controller",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-member-controller",
    "js/features/home/directives/HomeDirective.js~HomeDirective#controller",
    "member"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#controlleras",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-member-controllerAs",
    "js/features/home/directives/HomeDirective.js~HomeDirective#controllerAs",
    "member"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#link",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-method-link",
    "js/features/home/directives/HomeDirective.js~HomeDirective#link",
    "method"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#replace",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-member-replace",
    "js/features/home/directives/HomeDirective.js~HomeDirective#replace",
    "member"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#restrict",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-member-restrict",
    "js/features/home/directives/HomeDirective.js~HomeDirective#restrict",
    "member"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#scope",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-member-scope",
    "js/features/home/directives/HomeDirective.js~HomeDirective#scope",
    "member"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#templateurl",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-member-templateUrl",
    "js/features/home/directives/HomeDirective.js~HomeDirective#templateUrl",
    "member"
  ],
  [
    "js/features/home/directives/homedirective.js~homedirective#transclude",
    "class/js/features/home/directives/HomeDirective.js~HomeDirective.html#instance-member-transclude",
    "js/features/home/directives/HomeDirective.js~HomeDirective#transclude",
    "member"
  ],
  [
    "js/features/home/main.js",
    "file/js/features/home/main.js.html",
    "js/features/home/main.js",
    "file"
  ],
  [
    "js/features/home/main.js~feature#beforestart",
    "class/js/features/home/main.js~Feature.html#instance-method-beforeStart",
    "js/features/home/main.js~Feature#beforeStart",
    "method"
  ],
  [
    "js/features/home/main.js~feature#constructor",
    "class/js/features/home/main.js~Feature.html#instance-constructor-constructor",
    "js/features/home/main.js~Feature#constructor",
    "method"
  ],
  [
    "js/features/home/main.js~feature#execute",
    "class/js/features/home/main.js~Feature.html#instance-method-execute",
    "js/features/home/main.js~Feature#execute",
    "method"
  ],
  [
    "js/features/home/main.js~feature#routes",
    "class/js/features/home/main.js~Feature.html#instance-member-routes",
    "js/features/home/main.js~Feature#routes",
    "member"
  ],
  [
    "js/features/home/main.js~feature#templatecaching",
    "class/js/features/home/main.js~Feature.html#instance-method-templateCaching",
    "js/features/home/main.js~Feature#templateCaching",
    "method"
  ],
  [
    "js/features/main.js",
    "file/js/features/main.js.html",
    "js/features/main.js",
    "file"
  ],
  [
    "js/fw/config/appconfig.js",
    "file/js/fw/config/AppConfig.js.html",
    "js/fw/config/AppConfig.js",
    "file"
  ],
  [
    "js/fw/config/appconfig.js~configurator#config",
    "class/js/fw/config/AppConfig.js~Configurator.html#instance-member-config",
    "js/fw/config/AppConfig.js~Configurator#config",
    "member"
  ],
  [
    "js/fw/config/appconfig.js~configurator#constructor",
    "class/js/fw/config/AppConfig.js~Configurator.html#instance-constructor-constructor",
    "js/fw/config/AppConfig.js~Configurator#constructor",
    "method"
  ],
  [
    "js/fw/config/appconfig.js~configurator#execute",
    "class/js/fw/config/AppConfig.js~Configurator.html#instance-method-execute",
    "js/fw/config/AppConfig.js~Configurator#execute",
    "method"
  ],
  [
    "js/fw/config/notifierconfig.js",
    "file/js/fw/config/NotifierConfig.js.html",
    "js/fw/config/NotifierConfig.js",
    "file"
  ],
  [
    "js/fw/config/notifierconfig.js~configurator#constructor",
    "class/js/fw/config/NotifierConfig.js~Configurator.html#instance-constructor-constructor",
    "js/fw/config/NotifierConfig.js~Configurator#constructor",
    "method"
  ],
  [
    "js/fw/config/notifierconfig.js~configurator#execute",
    "class/js/fw/config/NotifierConfig.js~Configurator.html#instance-method-execute",
    "js/fw/config/NotifierConfig.js~Configurator#execute",
    "method"
  ],
  [
    "js/fw/config/notifierconfig.js~configurator#notifierconfig",
    "class/js/fw/config/NotifierConfig.js~Configurator.html#instance-method-notifierConfig",
    "js/fw/config/NotifierConfig.js~Configurator#notifierConfig",
    "method"
  ],
  [
    "js/fw/config/routerconfig.js",
    "file/js/fw/config/RouterConfig.js.html",
    "js/fw/config/RouterConfig.js",
    "file"
  ],
  [
    "js/fw/config/routerconfig.js~configurator#constructor",
    "class/js/fw/config/RouterConfig.js~Configurator.html#instance-constructor-constructor",
    "js/fw/config/RouterConfig.js~Configurator#constructor",
    "method"
  ],
  [
    "js/fw/config/routerconfig.js~configurator#execute",
    "class/js/fw/config/RouterConfig.js~Configurator.html#instance-method-execute",
    "js/fw/config/RouterConfig.js~Configurator#execute",
    "method"
  ],
  [
    "js/fw/config/routerconfig.js~configurator#routeconfig",
    "class/js/fw/config/RouterConfig.js~Configurator.html#instance-method-routeConfig",
    "js/fw/config/RouterConfig.js~Configurator#routeConfig",
    "method"
  ],
  [
    "js/fw/config/routerconfig.js~configurator#routes",
    "class/js/fw/config/RouterConfig.js~Configurator.html#instance-member-routes",
    "js/fw/config/RouterConfig.js~Configurator#routes",
    "member"
  ],
  [
    "js/fw/config/ssoconfig.js",
    "file/js/fw/config/SSOConfig.js.html",
    "js/fw/config/SSOConfig.js",
    "file"
  ],
  [
    "js/fw/config/ssoconfig.js~configurator#constructor",
    "class/js/fw/config/SSOConfig.js~Configurator.html#instance-constructor-constructor",
    "js/fw/config/SSOConfig.js~Configurator#constructor",
    "method"
  ],
  [
    "js/fw/config/ssoconfig.js~configurator#execute",
    "class/js/fw/config/SSOConfig.js~Configurator.html#instance-method-execute",
    "js/fw/config/SSOConfig.js~Configurator#execute",
    "method"
  ],
  [
    "js/fw/config/ssoconfig.js~configurator#httpconfig",
    "class/js/fw/config/SSOConfig.js~Configurator.html#instance-method-httpConfig",
    "js/fw/config/SSOConfig.js~Configurator#httpConfig",
    "method"
  ],
  [
    "js/fw/config/main.js",
    "file/js/fw/config/main.js.html",
    "js/fw/config/main.js",
    "file"
  ],
  [
    "js/fw/ext/main.js",
    "file/js/fw/ext/main.js.html",
    "js/fw/ext/main.js",
    "file"
  ],
  [
    "js/fw/init/body.js",
    "file/js/fw/init/Body.js.html",
    "js/fw/init/Body.js",
    "file"
  ],
  [
    "js/fw/init/body.js~initializer#constructor",
    "class/js/fw/init/Body.js~Initializer.html#instance-constructor-constructor",
    "js/fw/init/Body.js~Initializer#constructor",
    "method"
  ],
  [
    "js/fw/init/body.js~initializer#execute",
    "class/js/fw/init/Body.js~Initializer.html#instance-method-execute",
    "js/fw/init/Body.js~Initializer#execute",
    "method"
  ],
  [
    "js/fw/init/header.js",
    "file/js/fw/init/Header.js.html",
    "js/fw/init/Header.js",
    "file"
  ],
  [
    "js/fw/init/header.js~initializer#base",
    "class/js/fw/init/Header.js~Initializer.html#instance-method-base",
    "js/fw/init/Header.js~Initializer#base",
    "method"
  ],
  [
    "js/fw/init/header.js~initializer#constructor",
    "class/js/fw/init/Header.js~Initializer.html#instance-constructor-constructor",
    "js/fw/init/Header.js~Initializer#constructor",
    "method"
  ],
  [
    "js/fw/init/header.js~initializer#execute",
    "class/js/fw/init/Header.js~Initializer.html#instance-method-execute",
    "js/fw/init/Header.js~Initializer#execute",
    "method"
  ],
  [
    "js/fw/init/header.js~initializer#head",
    "class/js/fw/init/Header.js~Initializer.html#instance-member-head",
    "js/fw/init/Header.js~Initializer#head",
    "member"
  ],
  [
    "js/fw/init/header.js~initializer#meta",
    "class/js/fw/init/Header.js~Initializer.html#instance-method-meta",
    "js/fw/init/Header.js~Initializer#meta",
    "method"
  ],
  [
    "js/fw/init/header.js~initializer#title",
    "class/js/fw/init/Header.js~Initializer.html#instance-method-title",
    "js/fw/init/Header.js~Initializer#title",
    "method"
  ],
  [
    "js/fw/init/validator.js",
    "file/js/fw/init/Validator.js.html",
    "js/fw/init/Validator.js",
    "file"
  ],
  [
    "js/fw/init/validator.js~initializer#constructor",
    "class/js/fw/init/Validator.js~Initializer.html#instance-constructor-constructor",
    "js/fw/init/Validator.js~Initializer#constructor",
    "method"
  ],
  [
    "js/fw/init/validator.js~initializer#execute",
    "class/js/fw/init/Validator.js~Initializer.html#instance-method-execute",
    "js/fw/init/Validator.js~Initializer#execute",
    "method"
  ],
  [
    "js/fw/init/main.js",
    "file/js/fw/init/main.js.html",
    "js/fw/init/main.js",
    "file"
  ],
  [
    "js/fw/lib/apphttpresponseinterceptor.js",
    "file/js/fw/lib/AppHttpResponseInterceptor.js.html",
    "js/fw/lib/AppHttpResponseInterceptor.js",
    "file"
  ],
  [
    "js/fw/lib/apphttpresponseinterceptor.js~apphttpresponseinterceptor#constructor",
    "class/js/fw/lib/AppHttpResponseInterceptor.js~AppHttpResponseInterceptor.html#instance-constructor-constructor",
    "js/fw/lib/AppHttpResponseInterceptor.js~AppHttpResponseInterceptor#constructor",
    "method"
  ],
  [
    "js/fw/lib/apphttpresponseinterceptor.js~apphttpresponseinterceptor.httpauthfactory",
    "class/js/fw/lib/AppHttpResponseInterceptor.js~AppHttpResponseInterceptor.html#static-method-httpAuthFactory",
    "js/fw/lib/AppHttpResponseInterceptor.js~AppHttpResponseInterceptor.httpAuthFactory",
    "method"
  ],
  [
    "js/fw/lib/configuratorbase.js",
    "file/js/fw/lib/ConfiguratorBase.js.html",
    "js/fw/lib/ConfiguratorBase.js",
    "file"
  ],
  [
    "js/fw/lib/configuratorbase.js~configuratorbase#app",
    "class/js/fw/lib/ConfiguratorBase.js~ConfiguratorBase.html#instance-member-app",
    "js/fw/lib/ConfiguratorBase.js~ConfiguratorBase#app",
    "member"
  ],
  [
    "js/fw/lib/configuratorbase.js~configuratorbase#config",
    "class/js/fw/lib/ConfiguratorBase.js~ConfiguratorBase.html#instance-member-config",
    "js/fw/lib/ConfiguratorBase.js~ConfiguratorBase#config",
    "member"
  ],
  [
    "js/fw/lib/configuratorbase.js~configuratorbase#constant",
    "class/js/fw/lib/ConfiguratorBase.js~ConfiguratorBase.html#instance-member-constant",
    "js/fw/lib/ConfiguratorBase.js~ConfiguratorBase#constant",
    "member"
  ],
  [
    "js/fw/lib/configuratorbase.js~configuratorbase#constructor",
    "class/js/fw/lib/ConfiguratorBase.js~ConfiguratorBase.html#instance-constructor-constructor",
    "js/fw/lib/ConfiguratorBase.js~ConfiguratorBase#constructor",
    "method"
  ],
  [
    "js/fw/lib/configuratorbase.js~configuratorbase#execute",
    "class/js/fw/lib/ConfiguratorBase.js~ConfiguratorBase.html#instance-method-execute",
    "js/fw/lib/ConfiguratorBase.js~ConfiguratorBase#execute",
    "method"
  ],
  [
    "js/fw/lib/configuratorbase.js~configuratorbase#features",
    "class/js/fw/lib/ConfiguratorBase.js~ConfiguratorBase.html#instance-member-features",
    "js/fw/lib/ConfiguratorBase.js~ConfiguratorBase#features",
    "member"
  ],
  [
    "js/fw/lib/configuratorbase.js~configuratorbase#value",
    "class/js/fw/lib/ConfiguratorBase.js~ConfiguratorBase.html#instance-member-value",
    "js/fw/lib/ConfiguratorBase.js~ConfiguratorBase#value",
    "member"
  ],
  [
    "js/fw/lib/customfilters.js",
    "file/js/fw/lib/CustomFilters.js.html",
    "js/fw/lib/CustomFilters.js",
    "file"
  ],
  [
    "js/fw/lib/featurebase.js",
    "file/js/fw/lib/FeatureBase.js.html",
    "js/fw/lib/FeatureBase.js",
    "file"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#beforestart",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-method-beforeStart",
    "js/fw/lib/FeatureBase.js~FeatureBase#beforeStart",
    "method"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#config",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-member-config",
    "js/fw/lib/FeatureBase.js~FeatureBase#config",
    "member"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#constructor",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-constructor-constructor",
    "js/fw/lib/FeatureBase.js~FeatureBase#constructor",
    "method"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#controller",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-member-controller",
    "js/fw/lib/FeatureBase.js~FeatureBase#controller",
    "member"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#directive",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-member-directive",
    "js/fw/lib/FeatureBase.js~FeatureBase#directive",
    "member"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#execute",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-method-execute",
    "js/fw/lib/FeatureBase.js~FeatureBase#execute",
    "method"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#export",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-member-export",
    "js/fw/lib/FeatureBase.js~FeatureBase#export",
    "member"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#factory",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-member-factory",
    "js/fw/lib/FeatureBase.js~FeatureBase#factory",
    "member"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#filter",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-member-filter",
    "js/fw/lib/FeatureBase.js~FeatureBase#filter",
    "member"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#mod",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-member-mod",
    "js/fw/lib/FeatureBase.js~FeatureBase#mod",
    "member"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#run",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-member-run",
    "js/fw/lib/FeatureBase.js~FeatureBase#run",
    "member"
  ],
  [
    "js/fw/lib/featurebase.js~featurebase#service",
    "class/js/fw/lib/FeatureBase.js~FeatureBase.html#instance-member-service",
    "js/fw/lib/FeatureBase.js~FeatureBase#service",
    "member"
  ],
  [
    "js/fw/lib/initbase.js",
    "file/js/fw/lib/InitBase.js.html",
    "js/fw/lib/InitBase.js",
    "file"
  ],
  [
    "js/fw/lib/initbase.js~initbase#constructor",
    "class/js/fw/lib/InitBase.js~InitBase.html#instance-constructor-constructor",
    "js/fw/lib/InitBase.js~InitBase#constructor",
    "method"
  ],
  [
    "js/fw/lib/initbase.js~initbase#execute",
    "class/js/fw/lib/InitBase.js~InitBase.html#instance-method-execute",
    "js/fw/lib/InitBase.js~InitBase#execute",
    "method"
  ],
  [
    "js/fw/lib/initbase.js~initbase#features",
    "class/js/fw/lib/InitBase.js~InitBase.html#instance-member-features",
    "js/fw/lib/InitBase.js~InitBase#features",
    "member"
  ],
  [
    "js/fw/lib/omit.js",
    "file/js/fw/lib/Omit.js.html",
    "js/fw/lib/Omit.js",
    "file"
  ],
  [
    "js/fw/lib/pluck.js",
    "file/js/fw/lib/Pluck.js.html",
    "js/fw/lib/Pluck.js",
    "file"
  ],
  [
    "js/fw/lib/servicebase.js",
    "file/js/fw/lib/ServiceBase.js.html",
    "js/fw/lib/ServiceBase.js",
    "file"
  ],
  [
    "js/fw/lib/servicebase.js~servicebase#app",
    "class/js/fw/lib/ServiceBase.js~ServiceBase.html#instance-member-app",
    "js/fw/lib/ServiceBase.js~ServiceBase#app",
    "member"
  ],
  [
    "js/fw/lib/servicebase.js~servicebase#constructor",
    "class/js/fw/lib/ServiceBase.js~ServiceBase.html#instance-constructor-constructor",
    "js/fw/lib/ServiceBase.js~ServiceBase#constructor",
    "method"
  ],
  [
    "js/fw/lib/servicebase.js~servicebase#execute",
    "class/js/fw/lib/ServiceBase.js~ServiceBase.html#instance-method-execute",
    "js/fw/lib/ServiceBase.js~ServiceBase#execute",
    "method"
  ],
  [
    "js/fw/lib/servicebase.js~servicebase#factory",
    "class/js/fw/lib/ServiceBase.js~ServiceBase.html#instance-member-factory",
    "js/fw/lib/ServiceBase.js~ServiceBase#factory",
    "member"
  ],
  [
    "js/fw/lib/servicebase.js~servicebase#features",
    "class/js/fw/lib/ServiceBase.js~ServiceBase.html#instance-member-features",
    "js/fw/lib/ServiceBase.js~ServiceBase#features",
    "member"
  ],
  [
    "js/fw/lib/servicebase.js~servicebase#service",
    "class/js/fw/lib/ServiceBase.js~ServiceBase.html#instance-member-service",
    "js/fw/lib/ServiceBase.js~ServiceBase#service",
    "member"
  ],
  [
    "js/fw/service/customfilters.js",
    "file/js/fw/service/CustomFilters.js.html",
    "js/fw/service/CustomFilters.js",
    "file"
  ],
  [
    "js/fw/service/customfilters.js~customfilters#constructor",
    "class/js/fw/service/CustomFilters.js~CustomFilters.html#instance-constructor-constructor",
    "js/fw/service/CustomFilters.js~CustomFilters#constructor",
    "method"
  ],
  [
    "js/fw/service/customfilters.js~customfilters#execute",
    "class/js/fw/service/CustomFilters.js~CustomFilters.html#instance-method-execute",
    "js/fw/service/CustomFilters.js~CustomFilters#execute",
    "method"
  ],
  [
    "js/fw/service/customfilters.js~customfilters#playermarketvalue",
    "class/js/fw/service/CustomFilters.js~CustomFilters.html#instance-method-playerMarketValue",
    "js/fw/service/CustomFilters.js~CustomFilters#playerMarketValue",
    "method"
  ],
  [
    "js/fw/service/customfilters.js~customfilters#teamidfilter",
    "class/js/fw/service/CustomFilters.js~CustomFilters.html#instance-method-teamIDFilter",
    "js/fw/service/CustomFilters.js~CustomFilters#teamIDFilter",
    "method"
  ],
  [
    "js/fw/service/customfilters.js~customfilters.customfiltersfactory",
    "class/js/fw/service/CustomFilters.js~CustomFilters.html#static-method-CustomFiltersFactory",
    "js/fw/service/CustomFilters.js~CustomFilters.CustomFiltersFactory",
    "method"
  ],
  [
    "js/fw/service/events.js",
    "file/js/fw/service/Events.js.html",
    "js/fw/service/Events.js",
    "file"
  ],
  [
    "js/fw/service/events.js~service#constructor",
    "class/js/fw/service/Events.js~Service.html#instance-constructor-constructor",
    "js/fw/service/Events.js~Service#constructor",
    "method"
  ],
  [
    "js/fw/service/events.js~service#events",
    "class/js/fw/service/Events.js~Service.html#instance-method-events",
    "js/fw/service/Events.js~Service#events",
    "method"
  ],
  [
    "js/fw/service/events.js~service#execute",
    "class/js/fw/service/Events.js~Service.html#instance-method-execute",
    "js/fw/service/Events.js~Service#execute",
    "method"
  ],
  [
    "js/fw/service/footballdataservice.js",
    "file/js/fw/service/FootballDataService.js.html",
    "js/fw/service/FootballDataService.js",
    "file"
  ],
  [
    "js/fw/service/footballdataservice.js~footballdataservice#apikeys",
    "class/js/fw/service/FootballDataService.js~FootballDataService.html#instance-member-apiKeys",
    "js/fw/service/FootballDataService.js~FootballDataService#apiKeys",
    "member"
  ],
  [
    "js/fw/service/footballdataservice.js~footballdataservice#constructor",
    "class/js/fw/service/FootballDataService.js~FootballDataService.html#instance-constructor-constructor",
    "js/fw/service/FootballDataService.js~FootballDataService#constructor",
    "method"
  ],
  [
    "js/fw/service/footballdataservice.js~footballdataservice#execute",
    "class/js/fw/service/FootballDataService.js~FootballDataService.html#instance-method-execute",
    "js/fw/service/FootballDataService.js~FootballDataService#execute",
    "method"
  ],
  [
    "js/fw/service/footballdataservice.js~footballdataservice#makeapicall",
    "class/js/fw/service/FootballDataService.js~FootballDataService.html#instance-method-makeAPICall",
    "js/fw/service/FootballDataService.js~FootballDataService#makeAPICall",
    "method"
  ],
  [
    "js/fw/service/footballdataservice.js~footballdataservice#utils",
    "class/js/fw/service/FootballDataService.js~FootballDataService.html#instance-member-utils",
    "js/fw/service/FootballDataService.js~FootballDataService#utils",
    "member"
  ],
  [
    "js/fw/service/footballdataservice.js~footballdataservice.footballdatafactory",
    "class/js/fw/service/FootballDataService.js~FootballDataService.html#static-method-FootballDataFactory",
    "js/fw/service/FootballDataService.js~FootballDataService.FootballDataFactory",
    "method"
  ],
  [
    "js/fw/service/rssservice.js",
    "file/js/fw/service/RSSService.js.html",
    "js/fw/service/RSSService.js",
    "file"
  ],
  [
    "js/fw/service/rssservice.js~rssservice#constructor",
    "class/js/fw/service/RSSService.js~RSSService.html#instance-constructor-constructor",
    "js/fw/service/RSSService.js~RSSService#constructor",
    "method"
  ],
  [
    "js/fw/service/rssservice.js~rssservice#http",
    "class/js/fw/service/RSSService.js~RSSService.html#instance-member-http",
    "js/fw/service/RSSService.js~RSSService#http",
    "member"
  ],
  [
    "js/fw/service/rssservice.js~rssservice#parsefeed",
    "class/js/fw/service/RSSService.js~RSSService.html#instance-method-parseFeed",
    "js/fw/service/RSSService.js~RSSService#parseFeed",
    "method"
  ],
  [
    "js/fw/service/rssservice.js~rssservice.rssservicefactory",
    "class/js/fw/service/RSSService.js~RSSService.html#static-method-RSSServiceFactory",
    "js/fw/service/RSSService.js~RSSService.RSSServiceFactory",
    "method"
  ],
  [
    "js/fw/service/utils.js",
    "file/js/fw/service/Utils.js.html",
    "js/fw/service/Utils.js",
    "file"
  ],
  [
    "js/fw/service/utils.js~service#constructor",
    "class/js/fw/service/Utils.js~Service.html#instance-constructor-constructor",
    "js/fw/service/Utils.js~Service#constructor",
    "method"
  ],
  [
    "js/fw/service/utils.js~service#execute",
    "class/js/fw/service/Utils.js~Service.html#instance-method-execute",
    "js/fw/service/Utils.js~Service#execute",
    "method"
  ],
  [
    "js/fw/service/utils.js~service#formencodedopts",
    "class/js/fw/service/Utils.js~Service.html#instance-member-formEncodedOpts",
    "js/fw/service/Utils.js~Service#formEncodedOpts",
    "member"
  ],
  [
    "js/fw/service/utils.js~service#supportcanvas",
    "class/js/fw/service/Utils.js~Service.html#instance-member-supportCanvas",
    "js/fw/service/Utils.js~Service#supportCanvas",
    "member"
  ],
  [
    "js/fw/service/utils.js~service#utils",
    "class/js/fw/service/Utils.js~Service.html#instance-method-utils",
    "js/fw/service/Utils.js~Service#utils",
    "method"
  ],
  [
    "js/fw/service/main.js",
    "file/js/fw/service/main.js.html",
    "js/fw/service/main.js",
    "file"
  ],
  [
    "js/index.js",
    "file/js/index.js.html",
    "js/index.js",
    "file"
  ],
  [
    "js/main.js",
    "file/js/main.js.html",
    "js/main.js",
    "file"
  ],
  [
    "js/main.js~app#app",
    "class/js/main.js~App.html#instance-member-app",
    "js/main.js~App#app",
    "member"
  ],
  [
    "js/main.js~app#appname",
    "class/js/main.js~App.html#instance-member-appName",
    "js/main.js~App#appName",
    "member"
  ],
  [
    "js/main.js~app#beforestart",
    "class/js/main.js~App.html#instance-method-beforeStart",
    "js/main.js~App#beforeStart",
    "method"
  ],
  [
    "js/main.js~app#configapp",
    "class/js/main.js~App.html#instance-method-configApp",
    "js/main.js~App#configApp",
    "method"
  ],
  [
    "js/main.js~app#constructor",
    "class/js/main.js~App.html#instance-constructor-constructor",
    "js/main.js~App#constructor",
    "method"
  ],
  [
    "js/main.js~app#createapp",
    "class/js/main.js~App.html#instance-method-createApp",
    "js/main.js~App#createApp",
    "method"
  ],
  [
    "js/main.js~app#depends",
    "class/js/main.js~App.html#instance-member-depends",
    "js/main.js~App#depends",
    "member"
  ],
  [
    "js/main.js~app#destroysplash",
    "class/js/main.js~App.html#instance-method-destroySplash",
    "js/main.js~App#destroySplash",
    "method"
  ],
  [
    "js/main.js~app#features",
    "class/js/main.js~App.html#instance-member-features",
    "js/main.js~App#features",
    "member"
  ],
  [
    "js/main.js~app#finddependencies",
    "class/js/main.js~App.html#instance-method-findDependencies",
    "js/main.js~App#findDependencies",
    "method"
  ],
  [
    "js/main.js~app#launch",
    "class/js/main.js~App.html#instance-method-launch",
    "js/main.js~App#launch",
    "method"
  ],
  [
    "js/main.js~app#registerservice",
    "class/js/main.js~App.html#instance-method-registerService",
    "js/main.js~App#registerService",
    "method"
  ],
  [
    "js/main.js~app#run",
    "class/js/main.js~App.html#instance-method-run",
    "js/main.js~App#run",
    "method"
  ]
]